---

#copiar fichero de configuracion
- name: copiar fichero de configuracion
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/
    force: yes
  become: yes
  become_method: sudo

  # aplicar archivo k8s.conf
- name: aplicar archivo k8s.conf
  command: sysctl --system
  become: yes
  become_method: sudo

 # desactivar  swap
- name: desactivar swap
  command: swapoff  -a
  become: yes
  become_method: sudo

