---

# activar transparent masquerading 
- name: ejecutar modprobe
  command: /usr/bin/modprobe br_netfilter
  become: yes
  become_method: sudo

- name: ejecutar firewall masquerade 
  command: /usr/bin/firewall-cmd --add-masquerade --permanent
  become: yes
  become_method: sudo

# reiniciar firewall
- name: reiniciar firewall
  systemd:
    name: firewalld
    state: reloaded
  become: yes
  become_method: sudo