# abrir firewall
- name: abrir firewall nfs
  firewalld:
    service: nfs
    permanent: true
    state: enabled
  become: yes
  become_method: sudo

- name: abrir firewall  rpc-bind
  firewalld:
    service: rpc-bind
    permanent: true
    state: enabled
  become: yes
  become_method: sudo

- name: abrir firewall mountd
  firewalld:
    service: mountd
    permanent: true
    state: enabled
  become: yes
  become_method: sudo

- name: firewal reload
  command: /usr/bin/firewall-cmd --reload
  become: yes
  become_method: sudo


#validar que esta correcto
- name: firewal reload
  command: /usr/bin/showmount -e 192.168.0.110
  become: yes
  become_method: sudo