---

#crear particion para nfs
- name: crear una particion
  parted:
    device: "{{rutavolumen}}"
    number: 1
    state: present
  with_items:
        - "{{disco}}"
  register: particion_nfs
  become: yes
  become_method: sudo

#crear volumen
- name: crear grupo de volumen
  lvg:
    vg: "{{nombregrupovolumen}}"
    pvs: ["{{rutavolumenlogico}}"]
    force: no
    state: present
    when: particion_nfs.changed

#crear volumen logico
- name: crear volumen logico
  lvol:
    vg: "{{nombregrupovolumen}}"
    lv: nfs_lv
    size: 100%FREE
    force: no
    state: present
    when: particion_nfs.changed