---

#copiar fichero exports
- name: modificar fichero export
  copy:
    src: files/exports
    dest: /etc/
    force: yes
  become: yes
  become_method: sudo


# releer configuracion
- name: releer configuracion
  command: exportfs -r
  become: yes
  become_method: sudo

# releer configuracion
- name: releer configuracion 2
  command: exportfs -s
  become: yes
  become_method: sudo