---

# modificar el archivo exports
- name: modificar fichero export con 192.168.0.110
  lineinfile:
    path: /etc/exports
    line: '/srv/nfs	192.168.1.110(rw,sync)'
  become: yes
  become_method: sudo

- name: modificar fichero export con 192.168.0.111
  lineinfile:
    path: /etc/exports
    line: '/srv/nfs	192.168.0.111(rw,sync)'
  become: yes
  become_method: sudo


# releer configuracion
- name: releer configuracion
  command: /usr/bin/exportfs -r
  become: yes
  become_method: sudo

# releer configuracion
- name: releer configuracion 1
  command: /usr/bin/exportfs -r
  become: yes
  become_method: sudo

# releer configuracion
- name: releer configuracion 2
  command: /usr/bin/exportfs -s
  become: yes
  become_method: sudo