---

# se ha de ejecutar el siguiente comando para que el root pueda ejecutar kubectl
#- name: Activar al root para ejecutar kubectl
  #command: export KUBECONFIG=/etc/kubernetes/admin.conf
  #become: yes
  #become_method: sudo

# se ha de ejecutar el siguiente comando para que el root pueda ejecutar kubectl
# crear directorio Kube
- name: Crear directorio kube
  file:
    path: /root/.kube
    state: directory
  become: yes
  become_method: sudo

#copiar configuracion kube
- name: copiar configuracion kube
  command: sudo cp -i /etc/kubernetes/admin.conf /root/.kube/config
  become: yes
  become_method: sudo


# copiar configuracion kube y modificar propietario usuario
- name:   modificar  propietario
  file:
    path: /root/.kube/config
    owner: "{{ansible_user | default(ansible_user_id) }}"
    group: "{{ansible_user | default(ansible_user_id) }}"
    mode: 0755
  become: yes
  become_method: sudo
  #copy:
   # src: /etc/kubernetes/admin.conf
    #dest: /root/.kube/config
    #owner: "{{ansible_user | default(ansible_user_id) }}"
    #group: "{{ansible_user | default(ansible_user_id) }}"
    #mode: 0755
    #remote_src: no
  #become: yes
  #become_method: sudo
  #command: sudo chown $(id -u):$(id -g) /root/.kube/config
  #command: chown root. /root/.kube/config
  #become: yes
  #become_method: sudo

- name: Obtener nodos
  command: kubectl get nodes
  become: yes
  become_method: sudo