---

# se ha de ejecutar el siguiente comando para que el root pueda ejecutar kubectl
#- name: Activar al root para ejecutar kubectl
  #command: export KUBECONFIG=/etc/kubernetes/admin.conf
  #become: yes
  #become_method: sudo

# se ha de ejecutar el siguiente comando para que el root pueda ejecutar kubectl
# crear directorio Kube
- name: Crear directorio kube
  file:
    path: /root/.kube
    state: directory
  become: yes
  become_method: sudo

#copiar configuracion kube
#- name: Activar al root para ejecutar kubectl
 # command: cp -i /etc/kubernetes/admin.conf /root/.kube/config
  #become: yes
  #become_method: sudo


# copiar configuracion kube y modificar propietario usuario
- name: Activar al root para ejecutar kubectl y  modificar  propietario
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: "{{ansible_user | default(ansible_user_id) }}"
    group: "{{ansible_user | default(ansible_user_id) }}"
    mode: 0755
    #remote_src: true
  become: yes
  become_method: sudo
  #command: sudo chown $(id -u):$(id -g) /root/.kube/config
  #command: chown root. /root/.kube/config
  #become: yes
  #become_method: sudo

- name: Obtener nodos
  command: kubectl get nodes
  become: yes
  become_method: sudo