---

#instalar imagen de docker un
- name: Instalar docker-compose
  command: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
  register: tarea_completada
  become: yes
  become_method: sudo

- name: Instalar docker-compose
  command: 'sudo chmod +x /usr/local/bin/docker-compose'
  register: instalado
  become: yes
  become_method: sudo


#instalar imagen de docker un
- name: Instalar imagen de jenkins
  command: docker pull jenkins/jenkins:lts-jdk11
  register: tarea_completada
  become: yes
  become_method: sudo


- name: Ejecutar imagen de jenkins
  command: docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts-jdk11
  register: levantar el docker
  become: yes
  become_method: sudo

  when: variable_kubeadm.changed

#Ejecutar imagen de jenkins
- name: Ejecutar imagen de jenkins
  command: docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts-jdk11
  register: levantar el docker
  become: yes
  become_method: sudo


