---

# Instalamos el plugin CNI
- name: Instalamos el plugin CNI
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  register: variable_kubeadm
  become: yes
  become_method: sudo


- name: eliminar line
  lineinfile:
    path: ../../../group_vars/variablesmasteraworker.yaml
    regexp: 'salida_variable_kubeadm%'
    state: absent
    backup: yes
  become: yes
  become_method: sudo

- name: modificar linea
  lineinfile:
    path: /../group_vars/variablesmasteraworker.yaml
    line: "salida_variable_kubeadm: {{variable_kubeadm}}"
  become: yes
  become_method: sudo
