---

# Instalamos el plugin CNI
- name: Instalamos el plugin CNI
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  register: variable_kubeadm
  become: yes
  become_method: sudo
 

- name: Obtener el comando a ejecutar 
  set_fact:
   #error_lines: "{{ variable_kubeadm.results | to_json | from_json | json_query(\"[].stdout_lines[?contains(@, 'kubeadm')][]\")  }}"
   resultado: "{{ variable_kubeadm.stdout.split('\n').27 }}"

- name: Mostrar linea
  debug:
        var: resultado

- name: Guardar variable para despues utilzarla
  replace:
   path: "{{pathfichero}}/variablesmasteraworker.yaml"
   regexp: "remplazar"
   replace: "{{variable_kubeadm.stdout}}"
   #replace: resultado
  become: yes
  become_method: sudo
  when: variable_kubeadm.changed


#- name: modificar linea
  #lineinfile:
   # path: "{{pathfichero}}/variablesmasteraworker.yaml"
    #line: "salida_variable_kubeadm: {{variable_kubeadm}}"
  #become: yes
  #become_method: sudo
