---

# Instalamos el plugin CNI
- name: Instalamos el plugin CNI
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  register: variable_kubeadm
  become: yes
  become_method: sudo
 

#- name: copy fechero
 # template:
  #  src: variablesmasteraworker.yaml.j2
   # dest: "{{pathfichero}}/variablesmasteraworker.yaml"
    #owner: ansible
    #group: ansible
    #mode: 0644
    #vars:
     #   remplazar: {{variable_kubeadm.stdout}}
  #become: yes
  #become_method: sudo


- name: modificar variable
  replace:
   path: "{{pathfichero}}/variablesmasteraworker.yaml"
   regexp: "remplazar"
   replace: "{{variable_kubeadm.stdout}}"
  become: yes
  become_method: sudo
  when: variable_kubeadm.changed


#- name: modificar linea
  #lineinfile:
   # path: "{{pathfichero}}/variablesmasteraworker.yaml"
    #line: "salida_variable_kubeadm: {{variable_kubeadm}}"
  #become: yes
  #become_method: sudo
