#copiar fichero de configuracion de Kubernetes
- name: copiar fichero de configuracion repositorio kubernetes
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/
    force: yes
  become: yes
  become_method: sudo