---

#instalar imagen de docker un
- name: Instalar docker-compose
  command: pip3 install docker-compose
  register: tarea_completada
  become: yes
  become_method: sudo

#- name: Permisos docker-compose
 # command: 'sudo chmod +x /usr/local/bin/docker-compose'
  #register: instalado
  #become: yes
  #become_method: sudo

- name:  Permisos
  file:
    path: /usr/local/bin/docker-compose
    owner: "{{ansible_user | default(ansible_user_id) }}"
    group: "{{ansible_user | default(ansible_user_id) }}"
    mode: 0755
  become: yes
  become_method: sudo


- name: Instalar Jupyter
  command: 'git clone https://github.com/JuanLuisGozaloFdez/DevOpsLab4-jupyter'
  register: instaladojupyter
  become: yes
  become_method: sudo

- name: ir a ejecutardoker compose
  command: chdir=./DevOpsLab4-jupyter ls
  become: yes
  become_method: sudo

- name: Mostrar linea
  debug:
        var: instaladojupyter

- name: Ejecutar docker
  command: docker-compose up -d >> salida.txt
  register: salida
  become: yes
  become_method: sudo

