---
#abrir puestos para los workers
- name: abrir firewall  10250/tcp
  firewalld:
    port: 10250/tcp
    zone: public
    permanent: true
    state: enabled
  become: yes
  become_method: sudo

- name: abrir firewall  30000-32767/tcp
  firewalld:
    port: 30000-32767/tcp
    zone: public
    permanent: true
    state: enabled
  become: yes
  become_method: sudo

  # reiniciar firewall
- name: reiniciar firewall
  systemd:
    name: firewalld
    state: reloaded
  become: yes
  become_method: sudo

# unirse al cluster
- name: unir  al cluster
  command: "{{variable_kubeadm.stdout}}"
  become: yes
  become_method: sudo