version: "3.0"

services:
  jenkins:
  image: php:7-apache
    build:
      context: ./jupyter
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
      - "22:22"
    volumes:
      - ./runbooks:/runbooks
      - /home/${USER}/.ssh:/home/jovyan/.ssh
      - /tmp/data:/data