---


#instalar imagen de docker un
- name: Instalar imagen de jenkins
  command: docker pull jenkins/jenkins:lts-jdk11
  register: tarea_completada
  become: yes
  become_method: sudo


- name: Ejecutar imagen de jenkins
  command: docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts-jdk11 >> info.txt
  register: levantar
  become: yes
  become_method: sudo
  when: tarea_completada.changed




