---

# instalamos nfs-utils
- name: instalar nfs-utils
  dnf:
    name: nfs-utils
  become: yes
  become_method: sudo

# instalamos net-tools herramientas de red
- name: instalar net-tools
  dnf:
    name: net-tools
  become: yes
  become_method: sudo

# activamos el nfs-server
- name: activar nfs-server
  systemd:
    name: nfs-server
    enabled: yes
  become: yes
  become_method: sudo

# iniciamos el nfs-server
- name: iniciar nfs-server
  systemd:
    state: started
    name: nfs-server




