#configuraciones para la maquina worker
- name: configurar maquina worker
  hosts: worker
  gather_facts: false
  vars_files:
    - "group_vars/variablesmasteraworker.yaml, group_vars/variableruta.yaml"
  roles:
    - b21_abrir puertos_worker
