#configuraciones para la maquina worker para el ingress controller
- name: configurar maquina worker para ingress controller
  hosts: worker
  gather_facts: false
  vars_files:
    - "group_vars/ipsystema.yaml"
  roles:
    - b23_instalar_ingres_controller
    - b24_crear_usuario_admin_cluster