---

# instalamos el Chrony
- name: instalar Chrony
  dnf:
    name: chrony
  become: yes
  become_method: sudo

# activamos el Chrony
- name: activar chrony
  systemd:
    name: chrony
    enabled: yes
    state: started
  become: yes
  become_method: sudo