apiVersion: jenkins/lts-jdk11
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: webapp
        image: docker.io/jenkins/jenkins:lts-jdk11      
        ports:
        - containerPort: 8080
        - containerPort: 50000
